HOME: /exp/ssia/projects/icl_antilm_decoding
STANDARD_FP0: gen-{generator.name}{data.doclevel}-{logitsp.name}/{data.trainset}-{data.testset}/{model.model_size}-nprompts{sample_prompts.nprompts}-seed{seed}.{data.direction}
STANDARD_FP: format-{format.name}/{sample_prompts.name}/${STANDARD_FP0}
gen_fn: ${HOME}/generated/${STANDARD_FP}.csv.hyp 
res_fn: ${HOME}/results/${STANDARD_FP}.json
test_source_fn: ${HOME}/data/{data.testset}/subset_test/{data.direction}.{data.source}.txt
test_target_fn: ${HOME}/data/{data.testset}/subset_test/{data.direction}.{data.target}.txt
test_parallel_fn: ${HOME}/data/{data.testset}/subset_test/{data.direction}.csv 
used_prompts_fn: assets/{data.trainset}/nprompts{sample_prompts.nprompts}_seed{seed}.{data.direction}.txt
logits_analysis: ${HOME}/analysis/logits/${STANDARD_FP}.csv
