format:
    name: instr_none
    prefix_seed: 0
    header: ""
    L1_delim: 
        value: "<L1>:"
        type: "string"
        n_toks: 1
    L2_delim: 
        value: "<L2>:"
        type: "string"
        init: string
        n_toks: 1
    eos: ""
    sep: "\n"
    delim: prefix 
    sep_init: lang
    prefix_configs: ""
    weight_configs: ""
    join_tasks: raw
