format:
    name: instr_L1L2
    prefix_seed: 0
    header: "Translate <L1> to <L2>:" #fullstop(worse) and semicolon 1bleu diff 0 shot, #\n
    #header: "从中文翻译成英文:"
    #header: "Traduire le français en portugais:"
    L1_delim: 
        value: "<L1>:"
        type: "string"
        n_toks: 1
    L2_delim: 
        value: "<L2>:" # a spaec here is also bad. what's wrong w the tokenization
        type: "string"
        init: lang 
        n_toks: 1
    eos: ""
    sep: "\n"
#    delim: prefix 
#    sep_init: lang
# space after header semi-colon bad?
