format:
    name: instr_L2 
    prefix_seed: 0
    #header: "Traduire du français vers l'anglais:" #fullstop(worse) and semicolon 1bleu diff 0 shot, #\n
    header: "Traduzir português para inglês:"
    L1_delim: 
    #value: "français:"
        value: "português:"
        type: "string"
        n_toks: 1
    L2_delim: 
    #value: "l'anglais:" # a spaec here is also bad. what's wrong w the tokenization
        value: "inglês:"
        type: "string"
        init: lang 
        n_toks: 1
    eos: ""
    sep: "\n"
#    delim: prefix 
#    sep_init: lang
# space after header semi-colon bad?
