generator:
    name: beamsearch
    batch_size: 4
    # MBR and stuff will go here. 
hf_generator_configs:
    num_beams: 5
    repetition_penalty: 1.0
    do_sample: True
    temperature: 1
    top_p: 1
    num_return_sequences: 1
