generator:
    name: default
    batch_size: 4
    sample: greedy
    # MBR and stuff will go here. 
hf_generator_configs:
    num_beams: 1
    repetition_penalty: 1.0
    do_sample: True
    temperature: 1.0
    top_p: 1
    gen_tokens_len: 100
    window_len: 2000
    num_return_sequences: 1
